# Fonts
font_family Monolisa Nerd Font Mono
# font_family JetBrainsMono Nerd Font
bold_font auto
italic_font Maple Mono NF Italic
bold_italic_font auto
font_size 10.0

font_features MonoLisaNerdFontCompleteM-Regular +liga +ss02 +ss03

macos_colorspace displayp3

# Nerd Fonts v2.3.3
# symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono
# Kittens
# Mappings kitty controls for windows and tabs for vim-like command
map kitty_mod+h move_window left
map kitty_mod+j move_window down
map kitty_mod+k move_window up
map kitty_mod+l move_window right
map ctrl+g kitten hints --type=linenum --linenum-action=tab zed {path}:{line}

open_url_with ~/.config/kitty/open_smart.sh
detect_urls yes
mouse_map cmd+left release grabbed,ungrabbed mouse_click_url

cursor_shape block
cursor_trail 10
background_opacity 0.70
background_blur 10

# Hide taskbar or not
hide_window_decorations titlebar-only
# macos_titlebar_color background
# hide_macos_titlebar yes

# Mouse
mouse_hide_wait 3.0

# macOS tab switching
map cmd+shift+] next_tab
map cmd+shift+[ previous_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# macOS copy/paste
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# macOS cmd+arrow / opt+arrow navigation
map cmd+left send_text all \x01
map cmd+right send_text all \x05
map opt+left send_text all \x1bb
map opt+right send_text all \x1bf

# -- Tmux --
map ctrl+alt+tab next_tab
map ctrl+shift+alt+tab previous_tab
# Send Ctrl Tab and Ctrl + Shift + Tab for Tmux navigation
map ctrl+tab send_text all \x1b[27;5;9~
map ctrl+shift+tab send_text all \x1b[27;6;9~

# Tab bar
tab_bar_edge top
tab_bar_align center
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_margin_height 2.0 0.0
macos_menubar_title_max_length 20
tab_title_max_length 20
tab_title_template "{index}: {tab.active_exe}"

window_padding_width 2 10 5
window_margin_width 2 10 5

shell_integration enabled


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
